### ISSUE TITLE
start showoff after showoff serve : ":Public is no longer used to avoid overloading Module#public"

### ISSUE THREAD

**Issue by shockley** [schacon/showoff#209]
platform:
   Windows 7, Ruby 1.93 (by rails installer 2.2.1)
steps to reproduce:
   $ git clone (showoff-repo)
   $ cd (showoff-repo)
   $ gem install showoff
   $ showoff serve
expected behavior:
   I don't know, because this is my first time using it
actual behavior:
    $ showoff serve
    image sizing disabled - install rmagick
    pdf generation disabled - install pdfkit
    :public is no longer used to avoid overloading Module#public, use :public_dir in
    stead
            from d:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/showoff-0.7.0/
    lib/showoff.rb:39:in `<class:ShowOff>'
    You should include GLI::App instead
    GLI.run no longer works for GLI-2, you must just call`run(ARGV)' instead
    either fix your app, or use the latest GLI in the 1.x family

**Comment by jumanjiman** [comment]
try using https://github.com/puppetlabs/showoff
it works for me and seems to be well-maintained.

```
gem search -r | grep -i  'showoff.*pl'
```

**Comment by petere** [comment]
I can confirm that the puppetlabs version has this issue fixed.

**Comment by remyleone** [comment]
Any plan to merge that in the main repository ?

**Comment by robertmain** [comment]
Seems to be still broken for me(yes I am using the puppetlabs version)

$ showoff serve
:public is no longer used to avoid overloading Module#public, use :public_dir instead
        from /var/lib/gems/1.9.1/gems/showoff-0.7.0/lib/showoff.rb:39:in `<class:ShowOff>'
You should include GLI::App instead
GLI.run no longer works for GLI-2, you must just call`run(ARGV)' instead
either fix your app, or use the latest GLI in the 1.x family

**Comment by route** [comment]
Fixed on master

**Comment by remyleone** [comment]
Still broken for me

sieben@sieben-lincs:~/workspace/showoff|master ⇒  showoff serve
:public is no longer used to avoid overloading Module#public, use
:public_dir instead
 from /var/lib/gems/1.9.1/gems/showoff-0.7.0/lib/showoff.rb:39:in
`<class:ShowOff>'
You should include GLI::App instead
GLI.run no longer works for GLI-2, you must just call`run(ARGV)' instead
either fix your app, or use the latest GLI in the 1.x family

2013/9/1 Dmitry Vorotilin notifications@github.com

**Comment by route** [comment]
I'm using `bin/showoff` binary, so if you have to run it for some folder you have to do `path-to-repo/bin/showoff serve`

**Comment by kathgironpe** [comment]
@route that works. Thanks.

**Comment by nathanl** [comment]
Using master does fix this bug for me. Here's voting for a new release. :)
